export type Color =
    | 'white'
    | 'black'
    | 'background'
    | 'default100'
    | 'default200'
    | 'default300'
    | 'default400'
    | 'default500'
    | 'default600'
    | 'default700'
    | 'default800'
    | 'foreground'
    | 'divider'
    | 'focus'
    | 'red_background'
    | 'red_light'
    | 'red'
    | 'red_dark'
    | 'yellow_background'
    | 'yellow_light'
    | 'yellow'
    | 'yellow_dark'
    | 'green_background'
    | 'green_light'
    | 'green'
    | 'green_dark'
    | 'blue_background'
    | 'blue_light'
    | 'blue'
    | 'blue_dark'
    | 'violet_background'
    | 'violet_light'
    | 'violet'
    | 'violet_dark';

export type Theme = 'light' | 'dark';
export type ColorPalette = { [key in Color]: string };
export type ColorPaletteSet = { [key in Theme]: ColorPalette };
